### ISSUE TITLE
Its getting stopped when cell is loaded again.

### ISSUE THREAD

**Issue by ankitgarg135** [DholStudio/DSGradientProgressView#1]
I am using this view in UITableViewCell, but when tableView gets loaded again, Progress view stops.
Here is code : 
class scannerTableViewCell: UITableViewCell {
 
    @IBOutlet weak var progressView: DSGradientProgressView!

    override func awakeFromNib() {
        super.awakeFromNib()
        
        progressView.barColor = UIColor.theme()
        progressView.wait()
       
    }
}

**Comment by iabtyagi** [comment]
It doesn't look like a bug in the library to me. 
Try moving `progressView.wait()` in `prepareForReuse` method of UITableViewCell. 
If you happen to find a bug and a fix to it, feel free to submit a pull request.
