### ISSUE TITLE
Update of pod spec after changing code

### ISSUE THREAD

**Issue by sebbu** [DholStudio/DSGradientProgressView#4]
Could you please update the version in your pod spec after changing files (i.e. update for Swift 4.2

**Comment by pauluhn** [comment]
workaround for now: 
`pod 'DSGradientProgressView', :git => 'https://github.com/DholStudio/DSGradientProgressView.git'`

**Comment by iabtyagi** [comment]
I apologise for the delay but I am facing some issues with my CocoaPods account. Hope to resolve it soon. Meanwhile, please use the workaround given by pauluhn.
Thanks.

**Comment by iabtyagi** [comment]
This is done.
